# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Deploy Telegram Bot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Zip file
      run: |
        zip -r telegram-game-bot.zip bot.py

    - name: Copy Files to Remote Server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        source: "telegram-game-bot.zip"
        target: /home/telegramGame/archives

    - name: SSH into Server and Build App
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USERNAME }}
        password: ${{ secrets.DEPLOY_PASSWORD }}
        script: |
          cd /home/telegramGame/
          rm -r ./botBuild
          mkdir ./botBuild
          mkdir ./temp
          unzip ./archives/telegram-game-bot.zip -d ./temp
          cd ./temp
          pyinstaller --onefile bot.py
          cd ./dist
          mv ./main /home/telegramGame/botBuild/main
          cd /home/telegramGame
          rm -r ./temp